# Generated by Django 4.0 on 2025-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bg_cache',
            field=models.JSONField(default=dict),
        ),
    ]
